# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 22:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0002_auto_20170620_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='greeting',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
    ]
