# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0003_auto_20170620_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Cost_to_seller',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='Price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
